package com.example.myapplication.ui.navigation

import android.net.Uri

object AppRoutes {
    const val Login = "login"
    const val Admin = "admin"
    const val Profile = "profile"
    const val Home = "home"
    const val Notifications = "notifications"
    const val Clients = "clients"
    const val Users = "users"
    const val CreateUser = "users/create"
    const val EditUser = "users/{userId}/edit"
    const val Employees = "employees"
    const val CreateEmployee = "employees/create"
    const val EditEmployee = "employees/{employeeId}/edit"
    const val CreateClient = "clients/create"
    const val EditClient = "clients/{clientId}/edit"
    const val Motorcycles = "motorcycles"
    const val MotorcycleDetail = "motorcycles/{motorcycleId}"
    const val CreateMotorcycle = "motorcycles/create"
    const val EditMotorcycle = "motorcycles/{motorcycleId}/edit"
    const val Inventory = "inventory"
    const val Orders = "orders"
    const val Invoices = "invoices"
    const val CreateInvoice = "invoices/create"
    const val InvoiceDetail = "invoices/{invoiceId}"
    const val Reports = "reports"
    const val Audit = "audit"
    const val OrderDetail = "orders/{orderId}"
    const val CreateOrder = "orders/create"
    const val EditOrder = "orders/{orderId}/edit"

    fun orderDetail(id: String): String = "orders/${Uri.encode(id)}"
    fun editOrder(id: String): String = "orders/${Uri.encode(id)}/edit"
    fun motorcycleDetail(id: String): String = "motorcycles/${Uri.encode(id)}"
    fun editMotorcycle(id: String): String = "motorcycles/${Uri.encode(id)}/edit"
    fun invoiceDetail(id: String): String = "invoices/${Uri.encode(id)}"
    fun editClient(id: String): String = "clients/${Uri.encode(id)}/edit"
    fun editUser(id: String): String = "users/${Uri.encode(id)}/edit"
    fun editEmployee(id: String): String = "employees/${Uri.encode(id)}/edit"
}
